name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies (no optional)
        run: |
          npm ci --no-optional || npm install --no-optional

      - name: Install solidity analyzer for Linux
        if: runner.os == 'Linux'
        run: npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu

      - name: Compile
        run: npm run compile

      - name: Test
        run: npx hardhat test

  deploy:
    name: Deploy to Circle Layer Testnet
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install deps (no optional)
        run: |
          npm ci --no-optional || npm install --no-optional

      - name: Install solidity analyzer for Linux
        if: runner.os == 'Linux'
        run: npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu

      - name: Check PRIVATE_KEY is set
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          if [ -z "$PRIVATE_KEY" ]; then
            echo "Error: secrets.PRIVATE_KEY is not set"; exit 1;
          else
            echo "PRIVATE_KEY is present (length ${#PRIVATE_KEY})";
          fi

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npm run deploy

      - name: Export ABI
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: node scripts/exportAbi.js

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployments-${{ github.sha }}
          path: deployments/**