name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04

    # Эти переменные видны во всех шагах
    env:
      # Глобально говорим npm не ставить optional deps (fsevents)
      npm_config_optional: "false"
      # Секреты подтягиваем в env и дальше используем только env.*
      CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
      SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (skip optional)
        # Дублируем защиту флагом на случай старого lockfile
        run: |
          npm ci --omit=optional

      - name: Compile
        run: npx hardhat compile

      - name: Read SimpleStorage (optional)
        if: env.CIRCLE_RPC_URL != '' && env.SIMPLE_STORAGE != ''
        run: npx hardhat run --network circleLayerTestnet scripts/read.js

      - name: Set SimpleStorage (optional)
        if: env.CIRCLE_RPC_URL != '' && env.SIMPLE_STORAGE != '' && env.PRIVATE_KEY != ''
        run: VALUE=4242 npx hardhat run --network circleLayerTestnet scripts/set.js
