name: CI

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies (no optional)
        run: |
          npm ci --no-optional || npm install --no-optional

      - name: Compile
        run: npm run compile

      - name: Test
        run: npx hardhat test
