name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npx hardhat compile

      - name: Test
        run: npx hardhat test

      # ===== Optional: прочитать значение из SimpleStorage на тестнете =====
      - name: Read from testnet (optional)
        if: ${{ github.event_name != 'pull_request' && secrets.CIRCLE_RPC_URL != '' && secrets.SIMPLE_STORAGE != '' }}
        env:
          CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
          SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}
        run: npm run read

      # ===== Optional: записать значение в SimpleStorage на тестнете =====
      - name: Set on testnet (optional)
        if: ${{ github.event_name != 'pull_request' && secrets.CIRCLE_RPC_URL != '' && secrets.SIMPLE_STORAGE != '' && secrets.PRIVATE_KEY != '' }}
        env:
          CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}
          VALUE: "4242"
        run: npm run set
