name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    # Пробрасываем секреты в env и используем ИХ в if-условиях (НЕ secrets.*)
    env:
      CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
      SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}
      PRIVATE_KEY:    ${{ secrets.PRIVATE_KEY }}

      # Чуть “успокоим” npm в CI
      CI: "true"
      NPM_CONFIG_AUDIT: "false"
      NPM_CONFIG_FUND:  "false"
      # На Linux опциональные пакеты (включая fsevents) нам не нужны
      NPM_CONFIG_OPTIONAL: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show versions
        run: |
          node -v
          npm -v

      # На некоторых lockfile npm ci ругается на fsevents даже с omit=optional.
      # Делаем сначала ci с omit=optional, при фейле — fallback на npm i.
      - name: Install deps (skip optional)
        shell: bash
        run: |
          set -e
          echo "Trying: npm ci --omit=optional"
          if npm ci --omit=optional; then
            echo "npm ci OK"
          else
            echo "npm ci failed; falling back to 'npm i --omit=optional'"
            rm -rf node_modules
            npm i --omit=optional
          fi

      # У некоторых окружений Hardhat не подтягивает linux-бинарь анализатора.
      # Гарантируем его наличие.
      - name: Ensure Linux solidity analyzer present
        shell: bash
        run: |
          node -e "try{require.resolve('@nomicfoundation/solidity-analyzer-linux-x64-gnu');process.exit(0)}catch(e){process.exit(1)}" \
          || npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu

      - name: Compile
        run: npx hardhat compile

      # Дешёвый smoke-тест чтения; работает, если задан адрес контракта.
      - name: Smoke: read SimpleStorage
        if: env.SIMPLE_STORAGE != ''
        run: npx hardhat run --network circleLayerTestnet scripts/read.js

      # Если есть экспортёр ABI — вызовем его и приложим артефакт
      - name: Export ABI (optional)
        shell: bash
        run: |
          if [ -f scripts/exportAbi.js ]; then
            node scripts/exportAbi.js
          else
            echo "scripts/exportAbi.js not found — skipping"
          fi

      - name: Upload ABI artifact (if any)
        uses: actions/upload-artifact@v4
        if: hashFiles('abi/**') != ''
        with:
          name: simpleStorage-abi
          path: abi/

      # Полный E2E (меняет состояние) — только при ручном запуске
      - name: E2E set+read (manual only)
        if: github.event_name == 'workflow_dispatch' && env.PRIVATE_KEY != '' && env.SIMPLE_STORAGE != ''
        run: |
          VALUE=4242 npx hardhat run --network circleLayerTestnet scripts/set.js
          npx hardhat run --network circleLayerTestnet scripts/read.js
