name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (omit optional)
        run: npm ci --omit=optional || npm i --omit=optional

      # ⬇⬇⬇ ВАЖНО: ставим анализатор для Linux без сохранения
      - name: Install Hardhat analyzer (Linux)
        run: npm i -D --no-save @nomicfoundation/solidity-analyzer-linux-x64-gnu

      - name: Compile
        run: npx hardhat compile

      - name: Test
        run: npx hardhat test

  deploy:
    needs: build_test
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      EXPLORER_BASE: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (omit optional)
        run: npm ci --omit=optional || npm i --omit=optional

      # ⬇⬇⬇ Анализатор нужен и тут (деплой триггерит компиляцию)
      - name: Install Hardhat analyzer (Linux)
        run: npm i -D --no-save @nomicfoundation/solidity-analyzer-linux-x64-gnu

      - name: Deploy
        shell: bash
        run: |
          set -euo pipefail
          npm run -s deploy | tee deploy.log
          addr=$(sed -n 's/^SimpleStorage address: //p' deploy.log | tail -1)
          if [[ -z "$addr" ]]; then
            echo "::error::Couldn't parse SimpleStorage address from deploy output"
            cat deploy.log
            exit 1
          fi
          echo "SIMPLE_STORAGE=$addr"          >> "$GITHUB_ENV"
          echo "TRUFFLE_SIMPLE_STORAGE=$addr"  >> "$GITHUB_ENV"
          {
            echo "### Deployed SimpleStorage"
            echo
            echo "Address: $addr"
            if [[ -n "${EXPLORER_BASE:-}" ]]; then
              echo "Explorer: ${EXPLORER_BASE}/address/$addr"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
