name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIMPLE_STORAGE: ${{ vars.SIMPLE_STORAGE }}
      CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (Linux-safe, omit optional)
        shell: bash
        env:
          NPM_CONFIG_OPTIONAL: "false"
        run: |
          set -e
          # Устанавливаем зависимости. Если падение из-за EBADPLATFORM (fsevents на Linux) — продолжаем.
          npm ci --omit=optional || {
            echo "::warning::npm ci failed, checking for EBADPLATFORM in npm debug log…"
            if grep -q 'EBADPLATFORM' /home/runner/.npm/_logs/*-debug-0.log; then
              echo "::notice::Detected EBADPLATFORM for fsevents on Linux — ignoring and continuing."
            else
              echo "::error::npm ci failed for a different reason."; exit 1
            fi
          }
          npm prune --omit=optional
          npm ls fsevents || true

      - name: Ensure analyzer & Compile
        shell: bash
        run: |
          node -e "try{require.resolve('@nomicfoundation/solidity-analyzer-linux-x64-gnu');process.exit(0)}catch(e){process.exit(1)}" \
          || npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu
          npx hardhat compile

      - name: Export ABI for artifacts
        run: node scripts/exportAbi.js

      - name: List outputs
        run: |
          echo "## Files" >> $GITHUB_STEP_SUMMARY
          ls -la abi || true >> $GITHUB_STEP_SUMMARY
          ls -la deployments || true >> $GITHUB_STEP_SUMMARY
          ls -la artifacts/contracts/SimpleStorage.sol || true >> $GITHUB_STEP_SUMMARY

      # Загружаем ABI — должен быть всегда
      - name: Upload ABI
        uses: actions/upload-artifact@v4
        with:
          name: abi-${{ github.sha }}
          path: abi/SimpleStorage.json
          if-no-files-found: error
          retention-days: 7

      # Остальные артефакты — опционально
      - name: Upload deployment JSON (optional)
        uses: actions/upload-artifact@v4
        with:
          name: deployment-${{ github.sha }}
          path: deployments/**/SimpleStorage.json
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload hardhat artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-artifact-${{ github.sha }}
          path: artifacts/contracts/SimpleStorage.sol/SimpleStorage.json
          if-no-files-found: ignore
          retention-days: 7

      # Дешёвый smoke-тест чтения из сети — только если заданы адрес и RPC
      - name: "Smoke: read SimpleStorage (optional)"
        if: ${{ env.SIMPLE_STORAGE != '' && env.CIRCLE_RPC_URL != '' }}
        run: npx hardhat run --network circleLayerTestnet scripts/read.js
