name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      # пропускаем optional deps (дублируем в .npmrc)
      npm_config_optional: "false"
      CIRCLE_RPC_URL: ${{ env.CIRCLE_RPC_URL || secrets.CIRCLE_RPC_URL }}
      SIMPLE_STORAGE: ${{ env.SIMPLE_STORAGE || secrets.SIMPLE_STORAGE }}
      PRIVATE_KEY: ${{ env.PRIVATE_KEY || secrets.PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (skip optional)
        run: |
          npm ci --no-optional || npm ci --omit=optional

      - name: Compile
        run: npx hardhat compile

      - name: Read SimpleStorage (optional)
        if: env.CIRCLE_RPC_URL != '' && env.SIMPLE_STORAGE != ''
        run: npx hardhat run --network circleLayerTestnet scripts/read.js

      - name: Set SimpleStorage (optional)
        if: env.CIRCLE_RPC_URL != '' && env.SIMPLE_STORAGE != '' && env.PRIVATE_KEY != ''
        run: VALUE=4242 npx hardhat run --network circleLayerTestnet scripts/set.js
