name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # Прокидываем секреты в окружение шагов (НЕ используем secrets в "if")
    env:
      CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}
      # Глобально отключаем опциональные зависимости (fsevents и т.п.)
      npm_config_optional: "false"
      npm_config_ignore_optional: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show npm info
        run: |
          node -v
          npm -v
          npm config get optional
          npm config get ignore-optional

      # Ключевой шаг: ставим зависимости без optional; если ci падает — откатываемся на install
      - name: Install deps (skip optional; tolerate EBADPLATFORM)
        run: |
          set -e
          if [ -f package-lock.json ]; then
            echo "Using npm ci (omit optional)…"
            npm ci --omit=optional --no-audit || {
              echo "npm ci failed, fallback to npm install (omit optional)…"
              npm cache clean --force || true
              rm -rf node_modules || true
              npm install --omit=optional --no-audit
            }
          else
            echo "No package-lock.json; using npm install (omit optional)…"
            npm install --omit=optional --no-audit
          fi

      - name: Compile
        run: npx hardhat compile

      - name: Test
        run: npx hardhat test

      # Опциональный шаг чтения ончейна — выполняется только если секреты реально заданы.
      # Никаких выражений с secrets в if: проверяем в шелле.
      - name: Read on-chain (optional)
        run: |
          if [ -n "$CIRCLE_RPC_URL" ] && [ -n "$SIMPLE_STORAGE" ]; then
            echo "Secrets present -> running npm run read"
            npm run read || true
          else
            echo "Skipping read: CIRCLE_RPC_URL or SIMPLE_STORAGE is not set"
          fi
