name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (skip optional)
        run: |
          npm ci --omit=optional || npm install --omit=optional

      # На Linux раннере Hardhat иногда не подтягивает бинарник анализатора —
      # ставим его явно. На Windows/мacOS шаг просто пропускается.
      - name: Add Solidity analyzer (Linux)
        if: runner.os == 'Linux'
        run: npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu || true

      - name: Compile
        run: npx hardhat compile

      - name: Test
        run: npx hardhat test

  smoke-read:
    name: Smoke Read (optional)
    needs: build
    runs-on: ubuntu-latest

    # Прокидываем секреты в env. Так можно делать проверки по env в шагах,
    # не используя secrets.* в условиях job'а (чтобы не ловить ошибки парсера).
    env:
      CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
      PRIVATE_KEY:    ${{ secrets.PRIVATE_KEY }}
      SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (skip optional)
        run: |
          npm ci --omit=optional || npm install --omit=optional

      - name: Add Solidity analyzer (Linux)
        if: runner.os == 'Linux'
        run: npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu || true

      # Выполняем чтение только если ВСЕ переменные заданы и это не PR из форка
      - name: Read value from chain
        if: ${{ env.CIRCLE_RPC_URL && env.PRIVATE_KEY && env.SIMPLE_STORAGE && github.event_name != 'pull_request' }}
        run: npm run read
