name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIMPLE_STORAGE: ${{ vars.SIMPLE_STORAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (Linux-safe, omit optional)
        run: |
          set -e
          npm ci --omit=optional
          npm prune --omit=optional
          npm ls fsevents || true

      - name: Ensure analyzer & Compile
        shell: bash
        run: |
          node -e "try{require.resolve('@nomicfoundation/solidity-analyzer-linux-x64-gnu');process.exit(0)}catch(e){process.exit(1)}" \
          || npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu
          npx hardhat compile

      - name: Export ABI for artifacts
        run: node scripts/exportAbi.js

      - name: Upload ABI & deployment
        uses: actions/upload-artifact@v4
        with:
          name: abi-and-deployment-${{ github.sha }}
          path: |
            abi/SimpleStorage.json
            deployments/**/SimpleStorage.json
            artifacts/contracts/SimpleStorage.sol/SimpleStorage.json
          if-no-files-found: error
          retention-days: 7

      # Дешёвый smoke-тест: чтение, если задан адрес и RPC
      - name: Smoke: read SimpleStorage (optional)
        if: ${{ env.SIMPLE_STORAGE != '' && secrets.CIRCLE_RPC_URL != '' }}
        env:
          CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
        run: npx hardhat run --network circleLayerTestnet scripts/read.js
