name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      # Пробрасываем секреты в env (в if ниже используем только env.*, а не secrets.*)
      CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      SIMPLE_STORAGE: ${{ secrets.SIMPLE_STORAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Главное: ставим зависимости без optional (fsevents и т.п.)
      - name: Install deps (skip optional)
        env:
          npm_config_optional: "false"
          npm_config_ignore_optional: "true"
        run: |
          npm ci --omit=optional --no-audit --no-fund || \
          npm ci --no-optional --no-audit --no-fund || \
          npm install --no-optional --no-audit --no-fund

      - name: Compile
        run: npx hardhat compile

      - name: Test
        run: npx hardhat test

      # Дополнительные шаги — выполняются только если заданы нужные переменные.
      - name: Whoami (optional)
        if: ${{ env.PRIVATE_KEY != '' && env.CIRCLE_RPC_URL != '' }}
        run: npx hardhat run scripts/whoami.js --network circleLayerTestnet
        continue-on-error: true

      - name: Read value (optional)
        if: ${{ env.SIMPLE_STORAGE != '' && env.CIRCLE_RPC_URL != '' }}
        run: npx hardhat run scripts/read.js --network circleLayerTestnet
        continue-on-error: true

      - name: Deploy (optional on push)
        if: ${{ github.event_name == 'push' && env.PRIVATE_KEY != '' && env.CIRCLE_RPC_URL != '' }}
        run: npm run deploy
        continue-on-error: true
