name: Contract ops (read/set)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Operation"
        type: choice
        required: true
        options: [read, set]
        default: read
      value:
        description: "Value for set() (ignored for read)"
        required: false
        type: string

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      NETWORK: circleLayerTestnet
      SIMPLE_STORAGE: ${{ vars.SIMPLE_STORAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (Linux-safe, omit optional)
        run: |
          set -e
          npm ci --omit=optional
          npm prune --omit=optional
          npm ls fsevents || true

      - name: Ensure analyzer & compile
        shell: bash
        run: |
          node -e "try{require.resolve('@nomicfoundation/solidity-analyzer-linux-x64-gnu');process.exit(0)}catch(e){process.exit(1)}" \
          || npm i -D @nomicfoundation/solidity-analyzer-linux-x64-gnu
          npx hardhat compile

      # read
      - name: Read
        if: ${{ inputs.mode == 'read' && env.SIMPLE_STORAGE != '' }}
        env:
          CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
        run: npx hardhat run --network $NETWORK scripts/read.js

      # set
      - name: Set
        if: ${{ inputs.mode == 'set' && env.SIMPLE_STORAGE != '' && inputs.value != '' }}
        env:
          CIRCLE_RPC_URL: ${{ secrets.CIRCLE_RPC_URL }}
          PRIVATE_KEY:    ${{ secrets.PRIVATE_KEY }}
          VALUE:          ${{ inputs.value }}
        run: npx hardhat run --network $NETWORK scripts/set.js

      - name: Summary
        run: |
          echo "Contract: \`$SIMPLE_STORAGE\`" >> $GITHUB_STEP_SUMMARY
          echo "Mode: \`${{ inputs.mode }}\`" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ inputs.value }}" ]; then
            echo "Value: \`${{ inputs.value }}\`" >> $GITHUB_STEP_SUMMARY
          fi
